### ISSUE TITLE
Provide an example splunk-otel-go

### ISSUE THREAD

**Issue by jpOlivo-uala** [signalfx/splunk-otel-go#1264]
Would be very useful add some example on documentation about implement splunk-otel-go on golang functions running on lambda

**Comment by pellared** [comment]
PTAL https://github.com/signalfx/tracing-examples/tree/main/opentelemetry-tracing/opentelemetry-lambda

I also created https://github.com/signalfx/tracing-examples/pull/114

**Comment by pellared** [comment]
@jpOlivo-uala Was it helpful? Have you succeeded?

**Comment by jpOlivo-uala** [comment]
@pellared the example was very helpful, I instrumented a golang function on Lambda following this example. Thank very much!
