### ISSUE TITLE
Spans not nested under parent spans from otelgin library

### ISSUE THREAD

**Issue by akats7** [signalfx/splunk-otel-go#1277]
**Describe the issue**
Hi all, I noticed that the spans that are generated as part of the redigo instrumentation come up as their own parent spans, even though they are triggered further down the call stack. I am using the otel gin instrumentation and wanted to see if there was a way for them to be registered as child spans of the gin instrumentation.  

**Steps to reproduce the issue:**
For example:
With simple gin api application, if an api route triggers a db transaction which uses redigo, one span is created for the gin route and the other is created for the redigo client, but they are not linked. 

**Attempted solutions and workarounds**

**Expected behavior**
I would like to see the redigo span as a child span of the gin span.

**Environment**
Complete the following information:

- OS version: [Alpine3]
- Go version: [1.17]

**Comment by MrAlias** [comment]
When the conn is passed a `context.Context` it will use any span that context creates as a parent. Example [here](https://github.com/signalfx/splunk-otel-go/blob/6828081afa6a86b729a141cdb892dc40a0707120/instrumentation/github.com/gomodule/redigo/splunkredigo/example_test.go#L59-L63).

You will need to extract the `context.Context` from the `gin.Context` (e.g. `ginContext.Request.Context()`) and pass to the redigo conn usage.

**Comment by MrAlias** [comment]
> When the conn is passed a `context.Context` it will use any span that context creates as a parent. Example [here](https://github.com/signalfx/splunk-otel-go/blob/6828081afa6a86b729a141cdb892dc40a0707120/instrumentation/github.com/gomodule/redigo/splunkredigo/example_test.go#L59-L63).
> 
> You will need to extract the `context.Context` from the `gin.Context` (e.g. `ginContext.Request.Context()`) and pass to the redigo conn usage.

Please reopen if this did not solve your issue.
