### ISSUE TITLE
[Feature Request] Custom ID Generator

### ISSUE THREAD

**Issue by sergiopastan** [signalfx/splunk-otel-go#1377]
I wonder if there is a way to set a custom IDGenerator for SpanID and TraceID. According to this document: https://docs.splunk.com/Observability/gdi/get-data-in/application/go/troubleshooting/migrate-signalfx-go-to-otel.html#replace-startspanoption-instances 

> Span IDs are automatically set. If you require custom span IDs, create a custom IDGenerator.

But I can 't figure out how to do ir currently using distro.Run(...) Options.

In order to do it now I have to create a new TracerProvider with all the TracerProviderOptions in distro/otel.go Run function.

I think it would be useful to have an Option to add a custom IDGenerator to the initial instrumentation.

Thanks

**Comment by elouan-pt** [comment]
Sorry for tagging this as a bug. I think enhancement label would fit better

**Comment by sergiopastan** [comment]
closing this issue because it was added in this [PR](https://github.com/signalfx/splunk-otel-go/pull/2634)
