### ISSUE TITLE
`splunkpgx`: support `github.com/jackc/pgx/v5`

### ISSUE THREAD

**Issue by MrAlias** [signalfx/splunk-otel-go#2406]
https://pkg.go.dev/github.com/jackc/pgx/v5

**Comment by joshi-kamitsukasa** [comment]
We want to use v5 too. Please support it.

**Comment by aliakseip** [comment]
I am working on this issue.

**Comment by aliakseip** [comment]
I thinks this issue can be closed! 
Thanks @pellared

**Comment by pellared** [comment]
Closing. The new feature will be available in the next release.
