### ISSUE TITLE
`SetMeterProvider` panics if two connections are open

### ISSUE THREAD

**Issue by blkt** [signalfx/splunk-otel-go#3430]
**Describe the issue**
Dependabot opened the following PR upgrading several opentelemetry dependencies in an open source project I'm maintaining.
Accepting the change causes panics for some reasons that are unclear to me, but that I managed to reproduce in a simpler script [here](https://github.com/blkt/panicrepro).

Here's the list of upgrades.

| Package | From | To |
| --- | --- | --- |
| [go.opentelemetry.io/otel/exporters/prometheus](https://github.com/open-telemetry/opentelemetry-go) | `0.51.0` | `0.52.0` |
| [go.opentelemetry.io/otel/exporters/stdout/stdouttrace](https://github.com/open-telemetry/opentelemetry-go) | `1.29.0` | `1.30.0` |
| [go.opentelemetry.io/otel/sdk](https://github.com/open-telemetry/opentelemetry-go) | `1.29.0` | `1.30.0` |
| [go.opentelemetry.io/otel/sdk/metric](https://github.com/open-telemetry/opentelemetry-go) | `1.29.0` | `1.30.0` |
| [go.opentelemetry.io/otel/trace](https://github.com/open-telemetry/opentelemetry-go) | `1.29.0` | `1.30.0` |
| [go.opentelemetry.io/otel/metric](https://github.com/open-telemetry/opentelemetry-go) | `1.29.0` | `1.30.0` |

I am opening the issue in this project because it only manifests with this tracing library, and `splunk-otel-go` version `1.19.0` with otel libraries at version `1.29.0` did not manifest this behavior.

**Steps to reproduce the issue:**
Use https://github.com/blkt/panicrepro to reproduce.
Branch `main` panics.
Branch `working-version` does not panic.

**Attempted solutions and workarounds**
No workarounds were attempted.

**Expected behavior**
Opening two connections should not cause any sort of panic.

**Environment**
Complete the following information:

- OS version: macOS 14.6.1
- Go version: 1.23.1
- splunk-otel-go version: 1.20.0

**Comment by MrAlias** [comment]
This looks related to https://github.com/open-telemetry/opentelemetry-go/issues/5827

**Comment by pellared** [comment]
@blkt, are you still able to reproduce it with https://github.com/signalfx/splunk-otel-go/releases/tag/v1.22.0?

**Comment by blkt** [comment]
@pellared we're already using version `v1.22.0` in production, works for us.
https://github.com/mindersec/minder/blob/main/go.mod#L65-L66
