### ISSUE TITLE
splunkpgx: consistently use pgx/v4

### ISSUE THREAD

**Issue by cloneable** [signalfx/splunk-otel-go#476]
`sql.go` seems to import jackc/pgx (v3.6...) instead of importing jackc/pgx/v4.

**Comment by pellared** [comment]
https://github.com/signalfx/splunk-otel-go/blob/14c8e599d81cf33083820546f8dab3773272dc1c/instrumentation/github.com/jackc/pgx/splunkpgx/sql.go#L46-L48

**Comment by cloneable** [comment]
Yes, I mean line 46.

See #477.

**Comment by MrAlias** [comment]
Closed with https://github.com/signalfx/splunk-otel-go/pull/478
