### ISSUE TITLE
Redis is not showing in Splunk APM graph

### ISSUE THREAD

**Issue by nachogoca** [signalfx/splunk-otel-go#56]
Versions
```
github.com/go-redis/redis/v8 v8.8.2
github.com/go-redis/redis/extra/redisotel/v8 v8.8.2
go.opentelemetry.io/otel v0.20.0
go.opentelemetry.io/otel/trace v0.20.0
```

I tried integrating otel with go-redis, as shown in the documentation here https://redis.uptrace.dev/tracing/. But the APM dashboard where all the connections between services is shown is not showing the connection with the Redis instance. 
Before this library I was using the signalfx-go-tracing, and I was able to see the connections in the Splunk APM viewer.

This library injects the following tags https://github.com/go-redis/redis/blob/master/extra/redisotel/redisotel.go#L31

I even tried implementing my own hook, adding more tags, without success.
```
	ctx, span := t.tracer.Start(ctx, cmd.FullName())
	span.SetAttributes(
		attribute.String("span.kind", "client"),
		attribute.String("span.type", "redis"),
		attribute.String("component", "redis"),
		attribute.String("db.connection_string", "redis"),
		attribute.String("db.type", "redis"),
		attribute.String("db.instance", "0"),
		attribute.String("db.name", "0"),
		attribute.String("net.peer.name", "redis.dev.company.com"),
		attribute.String("net.peer.port", "6379"),
		attribute.String("peer.hostname", "redis.dev.company.com"),
		attribute.String("peer.port", "redis.dev.company.com"),
		attribute.String("service.name", "redis"),
		attribute.String("resource.name", "redis"),
		attribute.String("operation.name", "redis.command"),
		attribute.String("otel.library.name", "go-tracing"),
		attribute.String("db.system", "redis"),
		attribute.String("db.statement", rediscmd.CmdString(cmd)),
	)

```

**Comment by pellared** [comment]
Hello @nachogoca 👋 

I am sorry to hear about the problems. After a quick analysis, I have not found any apparent bug. 

Is it possible that you share a working example or the whole instrumentation setup code?

**Comment by nachogoca** [comment]
Hello :wave: 
It's working now! I didn't move any of the tags, so I guess It's supported now out of the box in Splunk APM. Thanks
