### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by ccoqueiro** [signalfx/splunk-otel-go#939]
Hello All,

We're trying to instrument a Golang app in Lamba and we're having the following error:

```
2022-05-18T22:27:55.962Z debug global/internal_logging.go:62 exporting spans {
"count": 7,
  "total_dropped": 0
}
2022-05-18T22:29:41.186Z error distro@v0.8.0/otel.go:70 OpenTelemetry error {
  "error": "Post \"[https://ingest.us1.signalfx.com/v2/trace\](https://ingest.us1.signalfx.com/v2/trace%5C)": context deadline exceeded"
}
[github.com/signalfx/splunk-otel-go/distro.Run.func1](http://github.com/signalfx/splunk-otel-go/distro.Run.func1)
/Users/juanolivera/go/pkg/mod/[github.com/signalfx/splunk-otel-go/distro@v0.8.0/otel.go:70](http://github.com/signalfx/splunk-otel-go/distro@v0.8.0/otel.go:70)
[go.opentelemetry.io/otel.ErrorHandlerFunc.Handle](http://go.opentelemetry.io/otel.ErrorHandlerFunc.Handle)
/Users/juanolivera/go/pkg/mod/[go.opentelemetry.io/otel@v1.7.0/error_handler.go:37](http://go.opentelemetry.io/otel@v1.7.0/error_handler.go:37)
[go.opentelemetry.io/otel.(*delegator).Handle](http://go.opentelemetry.io/otel.(*delegator).Handle)
/Users/juanolivera/go/pkg/mod/[go.opentelemetry.io/otel@v1.7.0/handler.go:44](http://go.opentelemetry.io/otel@v1.7.0/handler.go:44)
[go.opentelemetry.io/otel.Handle](http://go.opentelemetry.io/otel.Handle)
/Users/juanolivera/go/pkg/mod/[go.opentelemetry.io/otel@v1.7.0/handler.go:97](http://go.opentelemetry.io/otel@v1.7.0/handler.go:97)
[go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue](http://go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue)
/Users/juanolivera/go/pkg/mod/[go.opentelemetry.io/otel/sdk@v1.6.1/trace/batch_span_processor.go:283](http://go.opentelemetry.io/otel/sdk@v1.6.1/trace/batch_span_processor.go:283)
[go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1](http://go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1)
/Users/juanolivera/go/pkg/mod/[go.opentelemetry.io/otel/sdk@v1.6.1/trace/batch_span_processor.go:125](http://go.opentelemetry.io/otel/sdk@v1.6.1/trace/batch_span_processor.go:125)
```

This only happens when it's implement on lambda. When we test it locally (with the same environment variables) without running on lambda we have no problems, the export of the spans is done without problems and we can see it on splunk cloud observability

The environment variables:

<img width="953" alt="Screen Shot 2022-05-19 at 15 12 44" src="https://user-images.githubusercontent.com/4563706/169606008-9e514d1f-1265-4513-833d-dc406dd04e7f.png">

Thanks in advance

Cheers

**Comment by pellared** [comment]
Hey @ccoqueiro 👋 

The backslash at the end of the URL (`https://ingest.us1.signalfx.com/v2/trace\`) seems strange. Can you double-check the `OTEL_EXPORTER_JAEGER_ENDPOINT` value?

**Comment by ccoqueiro** [comment]
Hello @pellared!!
I will inform and test this settings with the client. Unfortunately, our champion is on vacation, we are trying to set up a meeting this week to finalize this matter. So I believe that there is a specific problem in the sdk opentlemetry for Go, I believe it is a communication problem, so I will terminate this ticket and we will open another ticket if we detect something relevant in the library. Thank you too much for the answers and support.
